# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identificate potential quadruplex forming sequences.
#'
#' Function for identification of all potential intramolecular quadruplex
#' patterns (PQS) in DNA sequence.
#'
#' @param subject DNAString object.
#' @param max_len Maximal lenth of PQS.
#' @param min_score Minimal PQS score.
#' @param run_min_len Minimal length of quadruplex run.
#' @param run_max_len Maximal length of quadruplex run.
#' @param loop_min_len Minimal length of quadruplex loop.
#' @param loop_max_len Maxmimal length of quadruplex loop.
#' @param tetrad_bonus Score bonus for one complete G tetrade.
#' @param bulge_penalty Penalization for a bulge in quadruplex run.
#' @param mismatch_penalty Penalization for a mismatch in tetrad.
#' @param run_re Regular expression specifying one run of quadruplex.
#' @param scoring_fns Vector of names representing internal scoring functions
#'   that should be applied on each PQS. This option is particularly usefull in
#'   case you intend to radically change the default behavior and specify your
#'   own scoring function. By setting an empty vector you can disable all
#'   internal scoring functions and have a full control above the underlying
#'   detection algorithm.
#' @param custom_scoring_fn Custom quadruplex scoring function. It takes the
#'   following 10 arguments: \code{subject} - Input DNAString object,
#'   \code{score} - implicit PQS score, \code{start} - PQS start position,
#'   \code{width} - PQS width, \code{loop_1} - start pos. of loop #1,
#'   \code{run_2} - start pos. of run #2, \code{loop_2} - start pos. of loop
#'   #2, \code{run_3} - start pos. of run #3, \code{loop_3} - start pos. of
#'   loop #3, \code{run_4} - start pos. of run #4. Return value of the function
#'   has to be new score represented as a single integer value. Note that this
#'   function is invoked after all internal scoring functions specified by
#'   \code{scoring_fns} are evaluated and only in the case PQS was assigned
#'   non-zero score (for performance reasons).
#' @param verbose Enables detailed output. Turn it on if you want to see all
#'   possible PQS found at each positions and not just the best one. It is
#'   highly recommended to use this option for debugging custom quadruplex
#'   scoring function. Each PQS is reported on separate row in the following
#'   format: \code{start cnt pqs_sequence score}, where \code{start} is the PQS
#'   starting position, \code{pqs_sequence} shows the PQS sequence structure
#'   with each run surrounded by square brackets and \code{score} is the score
#'   assigned to the particular PQS by all applied scoring functions.
#' @return \code{\link{PQSViews}} object
#'
#' @examples
#' pv <- pqsfinder(DNAString("CCCCCCGGGTGGGTGGGTGGGAAAA"))
#'
pqsfinder <- function(subject, max_len = 70L, min_score = 0L, run_min_len = 3L, run_max_len = 11L, loop_min_len = 0L, loop_max_len = 30L, tetrad_bonus = 20L, bulge_penalty = 10L, mismatch_penalty = 10L, run_re = "G{1,5}.{0,5}G{1,5}", scoring_fns = as.character( c("score_run_lengths", "score_run_content", "score_loop_lengths")), custom_scoring_fn = NULL, verbose = 0L) {
    .Call('pqsfinder_pqsfinder', PACKAGE = 'pqsfinder', subject, max_len, min_score, run_min_len, run_max_len, loop_min_len, loop_max_len, tetrad_bonus, bulge_penalty, mismatch_penalty, run_re, scoring_fns, custom_scoring_fn, verbose)
}

