# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identificate potential quadruplex forming sequences.
#'
#' Function for identification of all potential intramolecular quadruplex
#' patterns (PQS) in DNA sequence.
#'
#' @param subject DNAString object.
#' @param max_len Maximal lenth of PQS.
#' @param min_score Minimal PQS score.
#' @param run_min_len Minimal length of quadruplex run.
#' @param run_max_len Maximal length of quadruplex run.
#' @param loop_min_len Minimal length of quadruplex loop.
#' @param loop_max_len Maxmimal length of quadruplex loop.
#' @param g_bonus Score bonus for one complete G tetrade.
#' @param bulge_penalty Penalization for a bulge in quadruplex run.
#' @param mismatch_penalty Penalization for a mismatch in tetrad.
#' @param run_re Regular expression specifying one run of quadruplex.
#' @param user_fn Custom quadruplex scoring function. It takes the following 10
#' arguments: \code{subject} - Input DNAString object, \code{score} - implicit PQS score,
#' \code{start} - PQS start position, \code{width} - PQS width, \code{loop_1} - start pos. of loop #1,
#' \code{run_2} - start pos. of run #2, \code{loop_2} - start pos. of loop #2,
#' \code{run_3} - start pos. of run #3, \code{loop_3} - start pos. of loop #3,
#' \code{run_4} - start pos. of run #4. Return value of the function should be new score
#' represented as asingle integer value.
#' @param use_cache Use cache for low complexity regions?
#' @param use_re Use regular expression engine to validate quadruplex run?
#' @param use_prof Enables profiling.
#' @param debug Enables detailed debugging output. Turn it on if you want
#' to see all possible quadruplexes found at each positions and not just
#' the best one.
#' @return \code{\link{PQSViews}} object
#'
#' @examples
#' pv <- pqsfinder(DNAString("CCCCCCGGGTGGGTGGGTGGGAAAA"))
#'
pqsfinder <- function(subject, max_len = 70L, min_score = 0L, run_min_len = 3L, run_max_len = 11L, loop_min_len = 0L, loop_max_len = 30L, g_bonus = 20L, bulge_penalty = 10L, mismatch_penalty = 10L, run_re = "G{1,5}.{0,5}G{1,5}", user_fn = NULL, use_cache = 1L, use_re = 0L, use_prof = 0L, debug = 0L) {
    .Call('pqsfinder_pqsfinder', PACKAGE = 'pqsfinder', subject, max_len, min_score, run_min_len, run_max_len, loop_min_len, loop_max_len, g_bonus, bulge_penalty, mismatch_penalty, run_re, user_fn, use_cache, use_re, use_prof, debug)
}

